development:
  # adapter: mysql2
  # encoding: utf8
  # host: localhost
  # reconnect: false
  # database: ecwid_voog_sync_development
  # username: root
  # password:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ecwid_voog_sync_development
  pool: 5
  username: user
  password: pass

test:
  # adapter: mysql2
  # encoding: utf8
  # host: localhost
  # reconnect: false
  # database: ecwid_voog_sync_test
  # username: root
  # password:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ecwid_voog_sync_test
  pool: 5
  username: user
  password: pass

production:
  # adapter: mysql2
  # encoding: utf8
  # reconnect: false
  # database: ecwid_voog_sync_production
  # username: root
  # password:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ecwid_voog_sync_production
  pool: 5
  username: user
  password: pass
